apiVersion: zeebe.io/v1
kind: Workflow
metadata:
  name: workflow-test
spec:
  clusterName: my-zeebe-cluster
  workflowDefinitionName: "test"
  workflowDefinitionContent: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
                                                             <bpmn:definitions xmlns:bpmn=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:bpmndi=\"http://www.omg.org/spec/BPMN/20100524/DI\" xmlns:dc=\"http://www.omg.org/spec/DD/20100524/DC\" xmlns:zeebe=\"http://camunda.org/schema/zeebe/1.0\" xmlns:di=\"http://www.omg.org/spec/DD/20100524/DI\" id=\"Definitions_0mis58q\" targetNamespace=\"http://bpmn.io/schema/bpmn\" exporter=\"Zeebe Modeler\" exporterVersion=\"0.6.2\">
                                                             <bpmn:process id=\"test\" name=\"test\" isExecutable=\"true\">
                                                             <bpmn:startEvent id=\"StartEvent_1\">
                                                             <bpmn:outgoing>SequenceFlow_1x41soy</bpmn:outgoing>
                                                             </bpmn:startEvent>
                                                             <bpmn:serviceTask id=\"ServiceTask_1dirm0m\" name=\"Test Worker\">
                                                             <bpmn:extensionElements>
                                                             <zeebe:taskDefinition type=\"test\" />
                                                             </bpmn:extensionElements>
                                                             <bpmn:incoming>SequenceFlow_1x41soy</bpmn:incoming>
                                                             <bpmn:outgoing>SequenceFlow_1b61yex</bpmn:outgoing>
                                                             </bpmn:serviceTask>
                                                             <bpmn:sequenceFlow id=\"SequenceFlow_1x41soy\" sourceRef=\"StartEvent_1\" targetRef=\"ServiceTask_1dirm0m\" />
                                                             <bpmn:endEvent id=\"EndEvent_0t6jiev\">
                                                             <bpmn:incoming>SequenceFlow_1b61yex</bpmn:incoming>
                                                             </bpmn:endEvent>
                                                             <bpmn:sequenceFlow id=\"SequenceFlow_1b61yex\" sourceRef=\"ServiceTask_1dirm0m\" targetRef=\"EndEvent_0t6jiev\" />
                                                             </bpmn:process>
                                                             <bpmndi:BPMNDiagram id=\"BPMNDiagram_1\">
                                                             <bpmndi:BPMNPlane id=\"BPMNPlane_1\" bpmnElement=\"test\">
                                                             <bpmndi:BPMNShape id=\"_BPMNShape_StartEvent_2\" bpmnElement=\"StartEvent_1\">
                                                             <dc:Bounds x=\"179\" y=\"103\" width=\"36\" height=\"36\" />
                                                             </bpmndi:BPMNShape>
                                                             <bpmndi:BPMNShape id=\"ServiceTask_1dirm0m_di\" bpmnElement=\"ServiceTask_1dirm0m\">
                                                             <dc:Bounds x=\"265\" y=\"81\" width=\"100\" height=\"80\" />
                                                             </bpmndi:BPMNShape>
                                                             <bpmndi:BPMNEdge id=\"SequenceFlow_1x41soy_di\" bpmnElement=\"SequenceFlow_1x41soy\">
                                                             <di:waypoint x=\"215\" y=\"121\" />
                                                             <di:waypoint x=\"265\" y=\"121\" />
                                                             </bpmndi:BPMNEdge>
                                                             <bpmndi:BPMNShape id=\"EndEvent_0t6jiev_di\" bpmnElement=\"EndEvent_0t6jiev\">
                                                             <dc:Bounds x=\"415\" y=\"103\" width=\"36\" height=\"36\" />
                                                             </bpmndi:BPMNShape>
                                                             <bpmndi:BPMNEdge id=\"SequenceFlow_1b61yex_di\" bpmnElement=\"SequenceFlow_1b61yex\">
                                                             <di:waypoint x=\"365\" y=\"121\" />
                                                             <di:waypoint x=\"415\" y=\"121\" />
                                                             </bpmndi:BPMNEdge>
                                                             </bpmndi:BPMNPlane>
                                                             </bpmndi:BPMNDiagram>
                                                             </bpmn:definitions>"
