apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
    spec:
      restartPolicy: Never
      containers:
        - name: cdf-events
          image: "gcr.io/camunda-researchanddevelopment/cd-flow:0.0.10"
          script: |
            export CDF_SINK=http://backend.35.204.61.61.xip.io/api/events
            export ENV=dev
            echo $ENV
            #cdf service deployed --id zeebe-operator --version "{{ .Release.Version }}" --env $ENV